
services:
  backend:
    # Instead of building locally, pull from Docker Hub (or ECR, GitHub Container Registry, etc.)
    image: murshidmp/linkedin-assistant-be:latest
    platform: linux/amd64
    container_name: linkedin_assistant_backend

    # If you have environment variables, keep them:
    env_file:
      - .env

    environment:
      NODE_ENV: development
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

    depends_on:
      - db
      - redis

    # Expose your NestJS port
    ports:
      - "3010:3010"

  db:
    image: postgres:14-alpine
    container_name: linkedin_assistant_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: linkedin_assistant_redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  db_data:
  redis_data:
